### ISSUE TITLE
EchoMimic is open-sourced

### ISSUE THREAD

**Issue by lymhust** [JosephPai/Awesome-Talking-Face#15]
EchoMimic is capable of generating portrait videos not only by audios and facial landmarks individually, but also by a combination of both audios and selected facial landmarks.
Project link: https://badtobest.github.io/echomimic.html
GitHub link: https://github.com/BadToBest/EchoMimic
![image](https://github.com/JosephPai/Awesome-Talking-Face/assets/18476076/6b978812-bb5f-4e65-ab92-a9942f8a0dd9)

https://github.com/JosephPai/Awesome-Talking-Face/assets/18476076/73840a0a-c8d5-4f87-884f-4784ab5dbc61

**Comment by JosephPai** [comment]
@lymhust Super interesting work! It is now in our paper list.
