### ISSUE TITLE
 EMOTE: Emotional Speech- Driven Animation with Content- Emotion Disentanglement

### ISSUE THREAD

**Issue by radekd91** [JosephPai/Awesome-Talking-Face#8]
Please consider adding the following work to the list of 3D-based papers:
EMOTE: Emotional Speech- Driven Animation with Content- Emotion Disentanglement
https://emote.is.tue.mpg.de/ 

Thanks for maintaining the list. It is a great resource.

**Comment by JosephPai** [comment]
Added. Thanks for the recommendation!
